# Using https://vadosware.io/post/zero-to-continuous-integrated-testing-a-haskell-project-with-gitlab/


variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack"

cache:
  paths:
    - .stack
    - .stack-work
    - target

before_script:
  - apt-get update
  - apt-get install -y make xz-utils nodejs
  - wget -qO- https://get.haskellstack.org/ | sh

stages:
  - pages
  - build
  - test

build:
  stage: build
  script:
    - stack build --no-terminal

unit-test:
  stage: test
  script:
    - stack test --no-terminal

pages:
  stage: pages
  script:
  - cp -r website public
  - stack build --fast --no-terminal
  - stack hoogle --rebuild --no-terminal
  - cp -r .stack-work/dist/*/*/doc/html/strema public
  artifacts:
    paths:
    - public
    expire_in: 1 day
  only:
  - master

